"""Sovereign Synapse MCP Server.

Exposes the local ChromaDB Synapse vault to any MCP-compatible host (Cursor,
Claude Desktop, etc.) over stdio.

Tools
-----
search_synapses           Semantic search over indexed turns.
get_recent_context        Last N synapses sorted by original_timestamp (working memory).
reflect_on_memories       Identify strategic themes via Ollama (mxbai-embed-large + llm).
query_legacy_persona      Unbroken Voice — answer *as* the user using Sovereign_Persona.json
                          and Forensic Receipts (local Ollama only).
get_vault_policy          Read-only / Legacy Mode JSON (chroma_mutation_forbidden, error_code).

Run (stdio transport for Cursor):
    python mcp_server/server.py
or via uv:
    uv run mcp_server/server.py

Read-only / Legacy Mode (set ``SYNAPSE_MCP_READ_ONLY=1`` and/or
``SYNAPSE_LEGACY_MODE=1``) blocks all Chroma mutations; use with Unbroken Voice.
"""

from __future__ import annotations

import copy
import json
import logging
import os
import re
import sys
from pathlib import Path
from typing import Any

# Resolve project root so imports work whether server.py is run from repo root
# or from mcp_server/ directly.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import chromadb
import ollama
from chromadb.config import Settings
from mcp.server.fastmcp import FastMCP

from core.context_cleaner import ContextCleaner
from core.ollama_embed import embed_text

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CHROMA_PATH = os.environ.get(
    "SYNAPSE_CHROMA_PATH",
    str(_PROJECT_ROOT / "vault" / "chroma"),
)
COLLECTION_NAME = os.environ.get("SYNAPSE_COLLECTION", "synapses")
EMBEDDING_MODEL = os.environ.get("SYNAPSE_EMBED_MODEL", "mxbai-embed-large")
REFLECT_LLM = os.environ.get("SYNAPSE_REFLECT_LLM", "llama3")
CHUNK_SIZE = 800  # match core/vector_store.py
# Display-only cap; canonical structural_signal in metadata is never truncated.
DISPLAY_SUMMARY_MAX = 2000

# Limits for reflect_on_memories to prevent context-window overflow
REFLECT_MAX_SNIPPETS = 10
REFLECT_MAX_CHARS = 15_000

# Unbroken Voice: Legacy Persona file (generated by unbroken_voice.py)
PERSONA_PATH = os.environ.get(
    "SYNAPSE_PERSONA_PATH",
    str(_PROJECT_ROOT / "vault" / "Sovereign_Persona.json"),
)
# Local LLM for query_legacy_persona (as the user)
LEGACY_PERSONA_LLM = os.environ.get(
    "SYNAPSE_LEGACY_PERSONA_LLM",
    os.environ.get("SYNAPSE_REFLECT_LLM", "llama3"),
)
# When true, Chroma add/update/delete/upsert are refused (Sovereign Legacy Mode)
SYNAPSE_MCP_READ_ONLY = str(os.environ.get("SYNAPSE_MCP_READ_ONLY", "")).lower() in (
    "1",
    "true",
    "yes",
)
SYNAPSE_LEGACY_MODE = str(os.environ.get("SYNAPSE_LEGACY_MODE", "")).lower() in (
    "1",
    "true",
    "yes",
)
# Legacy Mode implies a read-only vault view for hosted interrogation
EFFECTIVE_READ_ONLY = bool(SYNAPSE_MCP_READ_ONLY or SYNAPSE_LEGACY_MODE)

os.environ["CHROMA_TELEMETRY_NOOP"] = "True"
logging.getLogger("chromadb.telemetry").setLevel(logging.CRITICAL)
_logger = logging.getLogger("synapse.mcp")

# ---------------------------------------------------------------------------
# ChromaDB connection  (lazy singleton, handles lock / missing collection)
# ---------------------------------------------------------------------------

_chroma_client: chromadb.PersistentClient | None = None
_collection: Any | None = None


def _embed(text: str) -> list[float]:
    """Embed text using the configured Ollama model."""
    text = text[:CHUNK_SIZE]
    try:
        vector = embed_text(EMBEDDING_MODEL, text)
    except AttributeError as e:
        raise RuntimeError(str(e)) from e
    if not vector:
        raise RuntimeError(f"Ollama returned no embeddings for model '{EMBEDDING_MODEL}'")
    return vector


def _format_hit(
    doc_id: str,
    document: str,
    metadata: dict[str, Any],
    distance: float | None,
) -> dict[str, Any]:
    """Convert a raw ChromaDB hit to a clean dict for MCP response (working memory)."""
    base_uuid = doc_id.split("#")[0]
    return {
        "synapse_id": base_uuid,
        "chunk_id": doc_id,
        "snippet": document[:600].strip() if document else "",
        "timestamp": str(metadata.get("original_timestamp", "")),
        "model": str(metadata.get("model", "")),
        "source": str(metadata.get("source", "")),
        "distance": round(distance, 4) if distance is not None else None,
    }


def _coerce_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() in ("true", "1", "yes")
    return bool(value)


def _forensic_receipt_from_metadata(metadata: dict[str, Any]) -> str:
    return str(
        metadata.get("forensic_receipt")
        or metadata.get("forensic_integrity")
        or "",
    )


def _prose_tax_redacted_from_metadata(metadata: dict[str, Any], body: str) -> bool:
    raw = metadata.get("prose_tax_redacted")
    if raw is not None:
        return _coerce_bool(raw)
    return not ContextCleaner.is_clean(body)


def _display_summary(text: str, max_len: int = DISPLAY_SUMMARY_MAX) -> str:
    """Short preview for hosts; never used for signature verification."""
    if not text:
        return ""
    if len(text) <= max_len:
        return text
    return text[:max_len]


def _structural_contract(
    doc_id: str,
    document: str,
    metadata: dict[str, Any],
    distance: float | None,
) -> dict[str, Any]:
    """Typed retrieval payload: metadata + distilled signal + forensic receipt_id."""
    base_uuid = doc_id.split("#")[0]
    body = document or ""
    stored_signal = metadata.get("structural_signal")
    if isinstance(stored_signal, str) and stored_signal.strip():
        canonical_signal = stored_signal.strip()
    else:
        canonical_signal = ContextCleaner.distill_signal(body)
    receipt_id = str(metadata.get("receipt_id") or metadata.get("uuid") or "")
    forensic_receipt = _forensic_receipt_from_metadata(metadata)
    prose_tax_redacted = _prose_tax_redacted_from_metadata(metadata, body)
    asset_metadata = {
        "uuid": str(metadata.get("uuid", receipt_id)),
        "receipt_id": receipt_id,
        "signature_hex": str(metadata.get("signature_hex", "")),
        "forensic_receipt": forensic_receipt,
        "prose_tax_redacted": prose_tax_redacted,
        "structural_signal": canonical_signal,
        "source": str(metadata.get("source", "")),
        "model": str(metadata.get("model", "")),
        "original_timestamp": str(metadata.get("original_timestamp", "")),
        "forensic_integrity": str(metadata.get("forensic_integrity", forensic_receipt)),
    }
    ledger_provenance = copy.deepcopy(asset_metadata)
    return {
        "contract_type": "sovereign_structural_contract",
        "receipt_id": receipt_id,
        "synapse_id": base_uuid,
        "chunk_id": doc_id,
        "metadata": asset_metadata,
        "provenance": ledger_provenance,
        "distilled_signal": canonical_signal,
        "distilled_signal_excerpt": _display_summary(canonical_signal),
        "distance": round(distance, 4) if distance is not None else None,
    }


class _ReadOnlyCollection:
    """Sovereign / Legacy Mode: forward only read API to Chroma; block mutations on the vault."""

    _MUTATING = frozenset({"add", "update", "delete", "upsert", "modify"})

    def __init__(self, inner: Any) -> None:
        self._inner = inner

    @property
    def name(self) -> str:
        return self._inner.name  # type: ignore[no-any-return]

    def count(self) -> int:
        return self._inner.count()  # type: ignore[no-any-return]

    def get(self, *args: Any, **kwargs: Any) -> Any:
        return self._inner.get(*args, **kwargs)

    def query(self, *args: Any, **kwargs: Any) -> Any:
        return self._inner.query(*args, **kwargs)

    def __getattr__(self, name: str) -> Any:
        if name in self._MUTATING:

            def _vault_read_only_violation(*_a: Any, **_k: Any) -> None:
                raise PermissionError(
                    "Sovereign Synapse vault is read-only (Legacy Mode: set "
                    "SYNAPSE_MCP_READ_ONLY=1 and/or SYNAPSE_LEGACY_MODE=1; "
                    "add/update/delete/upsert on Chroma are disabled).",
                )

            return _vault_read_only_violation
        return getattr(self._inner, name)


def _semantic_search_results(
    collection: Any,
    query: str,
    n_results: int,
    *,
    structural_contract: bool = False,
) -> list[dict[str, Any]] | str:
    """Chroma query + unique-file cap; return result dicts or an error string for JSON."""
    requested = n_results
    n_results = min(max(1, n_results), 50)
    if requested > 50:
        _logger.debug(
            "semantic search: n_results requested=%s capped to 50 (shared helper max)",
            requested,
        )
    if collection.count() == 0:
        return "empty"
    try:
        embedding = _embed(query)
    except Exception as e:
        return f"embed:{e!s}"

    fetch_n = max(n_results * 4, 10)
    try:
        raw = collection.query(
            query_embeddings=[embedding],
            n_results=min(fetch_n, collection.count()),
            include=["documents", "metadatas", "distances"],
        )
    except Exception as e:
        return f"query:{e!s}"

    hit_ids = raw.get("ids", [[]])[0]
    docs = raw.get("documents", [[]])[0]
    metas = raw.get("metadatas", [[]])[0]
    dists = raw.get("distances", [[]])[0]
    seen: set[str] = set()
    results: list[dict[str, Any]] = []
    formatter = _structural_contract if structural_contract else _format_hit
    for doc_id, doc, meta, dist in zip(hit_ids, docs, metas, dists):
        base = doc_id.split("#")[0]
        if base in seen:
            continue
        seen.add(base)
        results.append(formatter(doc_id, doc, meta or {}, dist))
        if len(results) >= n_results:
            break
    return results


def _get_collection() -> Any:
    """Return the ChromaDB collection, wrapped for read-only Legacy Mode when configured."""
    global _chroma_client, _collection
    if _collection is not None:
        return _collection

    try:
        _chroma_client = chromadb.PersistentClient(
            path=CHROMA_PATH,
            settings=Settings(anonymized_telemetry=False, allow_reset=True),
        )
        c = _chroma_client.get_collection(name=COLLECTION_NAME)
        if EFFECTIVE_READ_ONLY:
            c = _ReadOnlyCollection(c)
        _collection = c
        _logger.info(
            "Connected to ChromaDB at %s — collection '%s' (%d items)%s",
            CHROMA_PATH,
            COLLECTION_NAME,
            _collection.count(),
            " [READ-ONLY / Legacy Mode]" if EFFECTIVE_READ_ONLY else "",
        )
    except Exception as e:
        _logger.error("Failed to connect to ChromaDB: %s", e)
        raise

    return _collection


# ---------------------------------------------------------------------------
# MCP server
# ---------------------------------------------------------------------------

mcp = FastMCP(
    name="sovereign-synapse",
    instructions=(
        "You are connected to the Sovereign Synapse vault — a local-first archive of "
        "human–AI conversation turns. Use the provided tools to retrieve semantically "
        "relevant memories, recent context, reflective synthesis, and (when a "
        "Sovereign_Persona.json exists) the Unbroken Voice / legacy persona query with "
        "forensic synapse receipts. Use get_vault_policy to see if Chroma mutations are "
        "forbidden in Legacy / read-only mode."
    ),
)


@mcp.tool()
def get_vault_policy() -> str:
    """Return read-only / Legacy Mode policy for the embedded Chroma client.

    When ``chroma_mutation_forbidden`` is true, any call to add/update/delete/upsert
    on the collection raises :class:`PermissionError`. This tool does not mutate the vault;
    it exists so hosts can surface a structured check before custom write paths.

    Returns:
        JSON with ``chroma_mutation_forbidden`` and the env toggles.
    """
    return json.dumps(
        {
            "chroma_mutation_forbidden": EFFECTIVE_READ_ONLY,
            "set_via": {
                "SYNAPSE_MCP_READ_ONLY": bool(SYNAPSE_MCP_READ_ONLY),
                "SYNAPSE_LEGACY_MODE": bool(SYNAPSE_LEGACY_MODE),
            },
            "on_mutation": {
                "error_code": "VAULT_READ_ONLY",
                "python_exception": "PermissionError",
            },
        },
        indent=2,
    )


@mcp.tool()
def search_synapses(query: str, n_results: int = 5) -> str:
    """Search the Synapse vault for semantically relevant Structural Contracts.

    Each result is a typed payload (metadata + distilled_signal + receipt_id)
    per schemas/synapse_manifest.json — not raw conversational prose.

    Args:
        query:     Natural language search query.
        n_results: Number of unique-file results to return (default 5, max 50).

    Returns:
        JSON with Structural Contract results and similarity distance.
    """
    if not query.strip():
        return json.dumps({"error": "query must not be empty"})
    if n_results < 1:
        n_results = 1
    if n_results > 50:
        n_results = 50

    try:
        collection = _get_collection()
    except Exception as e:
        return json.dumps({"error": f"ChromaDB unavailable: {e}"})

    sr = _semantic_search_results(
        collection, query, n_results, structural_contract=True
    )
    if isinstance(sr, str):
        if sr == "empty":
            return json.dumps(
                {"results": [], "message": "Vault is empty — run index first."}
            )
        if sr.startswith("embed:"):
            return json.dumps({"error": f"Embedding failed: {sr[6:]}"})
        if sr.startswith("query:"):
            return json.dumps({"error": f"ChromaDB query error: {sr[6:]}"})
        return json.dumps({"error": str(sr)})

    return json.dumps(
        {
            "results": sr,
            "query": query,
            "returned": len(sr),
            "contract_schema": "schemas/synapse_manifest.json",
        },
        indent=2,
    )


@mcp.tool()
def get_recent_context(n: int = 10) -> str:
    """Retrieve the most recently indexed synapses as working memory.

    Sorts by original_timestamp (descending) across all indexed chunks,
    deduplicates to unique source files, and returns the top N.

    Args:
        n: Number of recent unique synapses to return (default 10, max 50).

    Returns:
        JSON array of recent synapses with snippet and timestamp.
    """
    if n < 1:
        n = 1
    if n > 50:
        n = 50

    try:
        collection = _get_collection()
    except Exception as e:
        return json.dumps({"error": f"ChromaDB unavailable: {e}"})

    count = collection.count()
    if count == 0:
        return json.dumps({"results": [], "message": "Vault is empty — run index first."})

    try:
        # Fetch the entire collection so the Python-side timestamp sort
        # finds the most recent entries across the whole vault, not just
        # a partial window that would miss older-inserted recent entries.
        raw = collection.get(
            limit=count,
            include=["documents", "metadatas"],
        )
    except Exception as e:
        return json.dumps({"error": f"ChromaDB fetch error: {e}"})

    chunk_ids = raw.get("ids") or []
    docs = raw.get("documents") or []
    metas = raw.get("metadatas") or []

    items = list(zip(chunk_ids, docs, metas))

    # Sort by original_timestamp descending (string ISO sort works for our format)
    items.sort(
        key=lambda t: str(t[2].get("original_timestamp", "") if t[2] else ""),
        reverse=True,
    )

    seen: set[str] = set()
    results: list[dict[str, Any]] = []
    for doc_id, doc, meta in items:
        base = doc_id.split("#")[0]
        if base in seen:
            continue
        seen.add(base)
        results.append(_format_hit(doc_id, doc or "", meta or {}, None))
        if len(results) >= n:
            break

    return json.dumps({"results": results, "returned": len(results)}, indent=2)


@mcp.tool()
def reflect_on_memories(snippets: list[str], focus: str = "") -> str:
    """Identify strategic themes and connections across retrieved memory snippets.

    Sends the snippets to a local Ollama LLM and asks it to surface 3 themes,
    patterns, or strategic insights — functioning as an internal reflection step.

    Input is capped to the first 10 snippets and 15,000 characters to prevent
    context-window overflows.

    Args:
        snippets: List of text snippets retrieved from the vault.
        focus:    Optional guiding question or topic for the reflection.

    Returns:
        JSON with the model's reflection text and the 3 identified themes.
    """
    if not snippets:
        return json.dumps({"error": "snippets list must not be empty"})

    # Guard: cap snippet count and total character length; track both limits.
    capped_snippets = snippets[:REFLECT_MAX_SNIPPETS]
    snippets_truncated = len(snippets) > REFLECT_MAX_SNIPPETS

    combined = "\n\n---\n\n".join(s.strip() for s in capped_snippets if s.strip())
    if not combined:
        return json.dumps({"error": "all snippets were empty"})

    chars_truncated = len(combined) > REFLECT_MAX_CHARS
    combined = combined[:REFLECT_MAX_CHARS]

    focus_line = f"\n\nFocus question: {focus}" if focus.strip() else ""
    prompt = (
        "You are a senior knowledge architect reviewing a set of memory excerpts "
        "from a personal knowledge vault. Each excerpt is a snippet of a past "
        "human–AI conversation.\n\n"
        "Your task:\n"
        "1. Identify exactly 3 strategic themes or meaningful connections present "
        "across these memories.\n"
        "2. For each theme, give it a concise title and a 2-3 sentence explanation.\n"
        "3. End with a single-sentence synthesis that captures the overarching insight.\n"
        f"{focus_line}\n\n"
        "=== MEMORY EXCERPTS ===\n\n"
        f"{combined}\n\n"
        "=== END EXCERPTS ===\n\n"
        "Respond in plain text. Be precise and strategic."
    )

    try:
        response = ollama.chat(
            model=REFLECT_LLM,
            messages=[{"role": "user", "content": prompt}],
        )
        reflection_text: str = response.message.content or ""
    except Exception as e:
        return json.dumps(
            {
                "error": f"Ollama LLM call failed: {e}",
                "hint": f"Ensure '{REFLECT_LLM}' is available: ollama pull {REFLECT_LLM}",
            }
        )

    # Best-effort: extract 3 theme titles from the response (lines with leading digits)
    theme_lines = re.findall(r"(?:^|\n)\s*(?:\d+[.)]\s*)(.+)", reflection_text)
    themes = [t.strip() for t in theme_lines[:3]] if theme_lines else []

    return json.dumps(
        {
            "reflection": reflection_text,
            "themes": themes,
            "snippet_count": len(capped_snippets),
            "truncated": snippets_truncated or chars_truncated,
            "truncation_reason": (
                "snippet_count_and_chars" if snippets_truncated and chars_truncated
                else "snippet_count" if snippets_truncated
                else "chars" if chars_truncated
                else None
            ),
            "llm": REFLECT_LLM,
        },
        indent=2,
    )


@mcp.tool()
def query_legacy_persona(query: str, n_evidence: int = 8) -> str:
    """Unbroken Voice: answer *as* the author using *Sovereign_Persona.json* + Forensic Receipts.

    Semantically searches the Chroma vault for the query, attaches the top *N* unique-synapse
    receipts to the user message, and calls a local Ollama model with
    ``legacy_system_prompt`` as the system context. The reply must ground opinions in
    cited ``synapse_id`` values. All runs locally (no cloud). Requires a generated persona
    file; see ``unbroken_voice.py``.

    Args:
        query: Question to pose to the legacy persona.
        n_evidence: Max unique files to retrieve as evidence (1–20, default 8).

    Returns:
        JSON with ``answer``, ``forensic_receipts`` (synapse_id, chunk_id, snippet_excerpt), and
        model metadata, or a structured error.
    """
    if not query.strip():
        return json.dumps({"error": "query must not be empty"})
    try:
        ne = int(n_evidence)
    except (TypeError, ValueError):
        ne = 8
    ne = min(max(1, ne), 20)

    persona_path = Path(PERSONA_PATH)
    if not persona_path.is_file():
        return json.dumps(
            {
                "error": f"Sovereign_Persona.json not found at {persona_path}",
                "hint": "From the repo root: python unbroken_voice.py -o vault/Sovereign_Persona.json",
            }
        )
    try:
        persona: dict[str, Any] = json.loads(persona_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        return json.dumps({"error": f"Could not read persona JSON: {e}"})
    system_prompt = (persona.get("legacy_system_prompt") or "").strip()
    if not system_prompt:
        return json.dumps(
            {
                "error": "legacy_system_prompt is empty in Sovereign_Persona.json",
                "hint": "Re-run unbroken_voice.py with an indexed vault and Ollama up.",
            }
        )

    try:
        collection = _get_collection()
    except Exception as e:
        return json.dumps({"error": f"ChromaDB unavailable: {e}"})

    sr = _semantic_search_results(collection, query, ne)
    if isinstance(sr, str):
        if sr == "empty":
            return json.dumps(
                {
                    "error": "Vault is empty; cannot build forensic receipts.",
                    "hint": "Index synapses, then re-run the legacy query.",
                }
            )
        if sr.startswith("embed:"):
            return json.dumps({"error": f"Embedding failed: {sr[6:]}"})
        if sr.startswith("query:"):
            return json.dumps({"error": f"ChromaDB query error: {sr[6:]}"})
        return json.dumps({"error": str(sr)})

    evidence_blocks: list[str] = []
    receipts_out: list[dict[str, Any]] = []
    for r in sr:
        sid = r["synapse_id"]
        sn = r.get("snippet", "") or ""
        evidence_blocks.append(
            f"**Forensic receipt** `synapse_id={sid}` `chunk_id={r.get('chunk_id', '')}`\n"
            f"```\n{sn}\n```\n"
        )
        receipts_out.append(
            {
                "synapse_id": sid,
                "chunk_id": r.get("chunk_id", ""),
                "snippet_excerpt": sn,
                "original_timestamp": r.get("timestamp", ""),
                "receipt_id": "",
            }
        )

    user_content = (
        f"**Question (answer in the author's voice, citing synapse_id for claims):**\n{query}\n\n"
        "**Retrieved evidence from the local vault (ground your answer in these only):**\n\n"
    ) + "\n\n".join(evidence_blocks)
    system_full = (
        system_prompt
        + "\n\n---\n**Navigator protocol:** Cite the relevant `synapse_id` when attributing a "
        "position. If a topic is not covered, say you lack evidence in that voice—do not fabricate."
    )
    try:
        response = ollama.chat(
            model=LEGACY_PERSONA_LLM,
            messages=[
                {"role": "system", "content": system_full},
                {"role": "user", "content": user_content},
            ],
        )
        answer = (response.message.content or "").strip()
    except Exception as e:
        return json.dumps(
            {
                "error": f"Ollama LLM call failed: {e}",
                "hint": f"Ensure '{LEGACY_PERSONA_LLM}' is available: ollama pull {LEGACY_PERSONA_LLM}",
            }
        )

    excerpt = system_prompt[:200] + "..." if len(system_prompt) > 200 else system_prompt
    return json.dumps(
        {
            "answer": answer,
            "forensic_receipts": receipts_out,
            "persona_urn": str(persona.get("id", "")),
            "legacy_system_prompt_excerpt": excerpt,
            "llm": LEGACY_PERSONA_LLM,
        },
        indent=2,
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def _main() -> None:
    """Configure logging and start the MCP server over stdio."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s [%(name)s] %(message)s")
    _logger.info("Starting Sovereign Synapse MCP server (stdio transport)")
    _logger.info("  ChromaDB path : %s", CHROMA_PATH)
    _logger.info("  Collection    : %s", COLLECTION_NAME)
    _logger.info("  Embed model   : %s", EMBEDDING_MODEL)
    _logger.info("  Reflect LLM   : %s", REFLECT_LLM)
    _logger.info("  Persona file  : %s", PERSONA_PATH)
    _logger.info("  Legacy LLM    : %s", LEGACY_PERSONA_LLM)
    if EFFECTIVE_READ_ONLY:
        _logger.info(
            "  Vault mode    : READ-ONLY (SYNAPSE_MCP_READ_ONLY or SYNAPSE_LEGACY_MODE) — "
            "Chroma mutations are disabled (Unbroken Voice / hosted interrogation)."
        )
    mcp.run(transport="stdio")


if __name__ == "__main__":
    _main()
